### ISSUE TITLE
Periods/full stops in zip name (from version number) cause add-on to fail installation.

### ISSUE THREAD

**Issue by Gerkinfeltser** [AlansCodeLog/blender-debugger-for-vscode#3]
OS: Windows 10
VS Code Version: 1.20.1
VS Code Python Extension Version: 2018.1.0
PTVSD Version: 3.0.0
`where python`: ...{user dir}...\AppData\Local\Programs\Python\Python35\python.exe
Does VS Code / Visual Studio connect to the troubleshooting script? Yes

## Notes:
VS Code Addon does not show up in the Blender Addons Preferences Tab though according to console it is installed correctly. Checking in the installed location also confirms it is indeed in what appears to be the correct location. No errors throw, the addon just won't show up in the Addons tab.

**Comment by alanscodelog** [comment]
Does this also happen if you reset Blender to factory defaults? Not just a regular reset though because that won't clear the add-ons properly, you have to go into `%APPDATA%\Blender Foundation\Blender` rename the version you're using to `2.xxBACKUP` or something, then start Blender and try to add the add-on.

If this works, then it's a problem with Blender, sometimes the startup file or your settings can get sort of corrupted (not exactly sure what happens but I've had lots of weird bugs solved by resetting my startup file and re-importing any assets from the old one). You can try adding the folders inside the backup back one at a time, then starting Blender to try to narrow down the problem.

**Comment by Gerkinfeltser** [comment]
Yep, tried that as well. Still no luck. :( Thanks for the quick reply though!

**Comment by alanscodelog** [comment]
Hmm weird, what version of Blender are you using?

Have you tried installing other add-ons, do they work?

Can you tell me the output of the following script. It will try to enable the addon if it exists.

```python
import bpy
import addon_utils

print("==START==")

folder_name = "blender-debugger-for-vscode-master"

found = folder_name in addon_utils.addons_fake_modules
if found == False:
    print("Not Installed")
    print(addon_utils.addons_fake_modules)
else:
    state = addon_utils.check(folder_name)
    print("State: " + str(state[0]), str(state[1]))
    if state[0] == False:
        print("Enabling")
        bpy.ops.wm.addon_enable(module=folder_name)
        state = addon_utils.check(folder_name)
        if state[0] == True and state[1] == True:
            print("Enabled", str(state))
        else:
            print("Problem Enabling", str(state))
    else:
        print("Already Enabled")
        
print("==END==")
```

**Comment by Gerkinfeltser** [comment]
Using vanilla 2.79 (latest stable). The script reports "Not Installed" (though is it ok to just cp & paste the script in the blender text editor & hit the "Run Script" button?

**Comment by alanscodelog** [comment]
Yes, that's fine, but can you paste the whole output from `==Start==` to `==End==`.

**Comment by Gerkinfeltser** [comment]
This is after a factory reset/settings nuke & installing only the vscode addon:

`==START==
Not Installed
{'io_scene_fbx': <module 'io_scene_fbx' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_fbx\\__init__.py'>, 'render_copy_settings': <module 'render_copy_settings' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\render_copy_settings\\__init__.py'>, 'blender_id': <module 'blender_id' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\blender_id\\__init__.py'>, 'mocap': <module 'mocap' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mocap\\__init__.py'>, 'add_advanced_objects_panels': <module 'add_advanced_objects_panels' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_advanced_objects_panels\\__init__.py'>, 'development_edit_operator': <module 'development_edit_operator' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\development_edit_operator.py'>, 'io_blend_utils': <module 'io_blend_utils' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_blend_utils\\__init__.py'>, 'space_view3d_display_tools': <module 'space_view3d_display_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_display_tools\\__init__.py'>, 'uv_magic_uv': <module 'uv_magic_uv' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\uv_magic_uv\\__init__.py'>, 'add_curve_ivygen': <module 'add_curve_ivygen' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_curve_ivygen.py'>, 'pie_menus_official': <module 'pie_menus_official' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\pie_menus_official\\__init__.py'>, 'object_grease_scatter': <module 'object_grease_scatter' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_grease_scatter.py'>, 'measureit': <module 'measureit' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\measureit\\__init__.py'>, 'object_skinify': <module 'object_skinify' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_skinify.py'>, 'io_mesh_stl': <module 'io_mesh_stl' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_mesh_stl\\__init__.py'>, 'io_import_dxf': <module 'io_import_dxf' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_import_dxf\\__init__.py'>, 'animation_add_corrective_shape_key': <module 'animation_add_corrective_shape_key' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\animation_add_corrective_shape_key.py'>, 'btrace': <module 'btrace' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\btrace\\__init__.py'>, 'io_coat3D': <module 'io_coat3D' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_coat3D\\__init__.py'>, 'mesh_custom_normals_tools': <module 'mesh_custom_normals_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_custom_normals_tools.py'>, 'sequencer_kinoraw_tools': <module 'sequencer_kinoraw_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\sequencer_kinoraw_tools\\__init__.py'>, 'curve_simplify': <module 'curve_simplify' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\curve_simplify.py'>, 'io_anim_c3d': <module 'io_anim_c3d' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_anim_c3d\\__init__.py'>, 'ui_layer_manager': <module 'ui_layer_manager' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui_layer_manager.py'>, 'io_export_unreal_psk_psa': <module 'io_export_unreal_psk_psa' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_export_unreal_psk_psa.py'>, 'add_mesh_BoltFactory': <module 'add_mesh_BoltFactory' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_mesh_BoltFactory\\__init__.py'>, 'space_view3d_math_vis': <module 'space_view3d_math_vis' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_math_vis\\__init__.py'>, 'io_curve_svg': <module 'io_curve_svg' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_curve_svg\\__init__.py'>, 'space_clip_editor_refine_solution': <module 'space_clip_editor_refine_solution' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_clip_editor_refine_solution.py'>, 'io_mesh_raw': <module 'io_mesh_raw' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_mesh_raw\\__init__.py'>, 'rigify': <module 'rigify' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\rigify\\__init__.py'>, 'oscurart_tools': <module 'oscurart_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\oscurart_tools\\__init__.py'>, 'object_fracture_crack': <module 'object_fracture_crack' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_fracture_crack\\__init__.py'>, 'io_sequencer_edl': <module 'io_sequencer_edl' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_sequencer_edl\\__init__.py'>, 'space_view3d_3d_navigation': <module 'space_view3d_3d_navigation' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_3d_navigation.py'>, 'development_iskeyfree': <module 'development_iskeyfree' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\development_iskeyfree.py'>, 'mesh_extra_tools': <module 'mesh_extra_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_extra_tools\\__init__.py'>, 'bone_selection_sets': <module 'bone_selection_sets' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\bone_selection_sets.py'>, 'uv_bake_texture_to_vcols': <module 'uv_bake_texture_to_vcols' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\uv_bake_texture_to_vcols.py'>, 'system_blend_info': <module 'system_blend_info' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\system_blend_info.py'>, 'space_view3d_spacebar_menu': <module 'space_view3d_spacebar_menu' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_spacebar_menu.py'>, 'paint_palette': <module 'paint_palette' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\paint_palette.py'>, 'materials_library_vx': <module 'materials_library_vx' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\materials_library_vx\\__init__.py'>, 'io_online_sketchfab': <module 'io_online_sketchfab' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_online_sketchfab\\__init__.py'>, 'space_view3d_modifier_tools': <module 'space_view3d_modifier_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_modifier_tools.py'>, 'io_import_scene_lwo': <module 'io_import_scene_lwo' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_import_scene_lwo.py'>, 'add_advanced_objects_menu': <module 'add_advanced_objects_menu' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_advanced_objects_menu\\__init__.py'>, 'mesh_bsurfaces': <module 'mesh_bsurfaces' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_bsurfaces.py'>, 'development_ui_classes': <module 'development_ui_classes' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\development_ui_classes.py'>, 'add_mesh_extra_objects': <module 'add_mesh_extra_objects' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_mesh_extra_objects\\__init__.py'>, 'io_scene_x': <module 'io_scene_x' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_x\\__init__.py'>, 'add_curve_sapling': <module 'add_curve_sapling' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_curve_sapling\\__init__.py'>, 'game_engine_save_as_runtime': <module 'game_engine_save_as_runtime' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\game_engine_save_as_runtime.py'>, 'mesh_carver': <module 'mesh_carver' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_carver.py'>, 'mesh_snap_utilities_line': <module 'mesh_snap_utilities_line' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_snap_utilities_line.py'>, 'io_anim_nuke_chan': <module 'io_anim_nuke_chan' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_anim_nuke_chan\\__init__.py'>, 'mesh_relax': <module 'mesh_relax' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_relax.py'>, 'object_boolean_tools': <module 'object_boolean_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_boolean_tools.py'>, 'object_cloud_gen': <module 'object_cloud_gen' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_cloud_gen.py'>, 'mesh_f2': <module 'mesh_f2' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_f2.py'>, 'io_anim_camera': <module 'io_anim_camera' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_anim_camera.py'>, 'object_print3d_utils': <module 'object_print3d_utils' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_print3d_utils\\__init__.py'>, 'io_export_after_effects': <module 'io_export_after_effects' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_export_after_effects.py'>, 'system_property_chart': <module 'system_property_chart' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\system_property_chart.py'>, 'io_export_paper_model': <module 'io_export_paper_model' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_export_paper_model.py'>, 'archipack': <module 'archipack' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\archipack\\__init__.py'>, 'development_icon_get': <module 'development_icon_get' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\development_icon_get.py'>, 'archimesh': <module 'archimesh' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\archimesh\\__init__.py'>, 'render_freestyle_svg': <module 'render_freestyle_svg' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\render_freestyle_svg.py'>, 'io_scene_x3d': <module 'io_scene_x3d' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_x3d\\__init__.py'>, 'lighting_dynamic_sky': <module 'lighting_dynamic_sky' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\lighting_dynamic_sky.py'>, 'space_view3d_stored_views': <module 'space_view3d_stored_views' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_stored_views\\__init__.py'>, 'system_demo_mode': <module 'system_demo_mode' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\system_demo_mode\\__init__.py'>, 'object_animrenderbake': <module 'object_animrenderbake' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_animrenderbake.py'>, 'io_mesh_pdb': <module 'io_mesh_pdb' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_mesh_pdb\\__init__.py'>, 'mesh_auto_mirror': <module 'mesh_auto_mirror' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_auto_mirror.py'>, 'cycles': <module 'cycles' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\cycles\\__init__.py'>, 'camera_turnaround': <module 'camera_turnaround' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\camera_turnaround.py'>, 'netrender': <module 'netrender' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\netrender\\__init__.py'>, 'materials_utils': <module 'materials_utils' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\materials_utils\\__init__.py'>, 'game_engine_publishing': <module 'game_engine_publishing' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\game_engine_publishing.py'>, 'animation_animall': <module 'animation_animall' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\animation_animall.py'>, 'uv_texture_atlas': <module 'uv_texture_atlas' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\uv_texture_atlas.py'>, 'io_import_gimp_image_to_scene': <module 'io_import_gimp_image_to_scene' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_import_gimp_image_to_scene.py'>, 'camera_dolly_crane_rigs': <module 'camera_dolly_crane_rigs' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\camera_dolly_crane_rigs.py'>, 'io_scene_ms3d': <module 'io_scene_ms3d' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_ms3d\\__init__.py'>, 'light_field_tools': <module 'light_field_tools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\light_field_tools\\__init__.py'>, 'io_scene_obj': <module 'io_scene_obj' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_obj\\__init__.py'>, 'render_clay': <module 'render_clay' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\render_clay.py'>, 'space_clip_editor_autotracker': <module 'space_clip_editor_autotracker' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_clip_editor_autotracker.py'>, 'io_scene_vrml2': <module 'io_scene_vrml2' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_vrml2\\__init__.py'>, 'space_view3d_brush_menus': <module 'space_view3d_brush_menus' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_brush_menus\\__init__.py'>, 'ant_landscape': <module 'ant_landscape' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ant_landscape\\__init__.py'>, 'render_povray': <module 'render_povray' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\render_povray\\__init__.py'>, 'io_mesh_ply': <module 'io_mesh_ply' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_mesh_ply\\__init__.py'>, 'ui_translate': <module 'ui_translate' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\ui_translate\\__init__.py'>, 'mesh_tissue': <module 'mesh_tissue' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_tissue\\__init__.py'>, 'io_anim_acclaim': <module 'io_anim_acclaim' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_anim_acclaim\\__init__.py'>, 'io_anim_bvh': <module 'io_anim_bvh' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_anim_bvh\\__init__.py'>, 'object_fracture': <module 'object_fracture' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_fracture\\__init__.py'>, 'io_export_dxf': <module 'io_export_dxf' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_export_dxf\\__init__.py'>, 'space_view3d_pie_menus': <module 'space_view3d_pie_menus' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_pie_menus\\__init__.py'>, 'io_convert_image_to_mesh_img': <module 'io_convert_image_to_mesh_img' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_convert_image_to_mesh_img\\__init__.py'>, 'add_curve_extra_objects': <module 'add_curve_extra_objects' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\add_curve_extra_objects\\__init__.py'>, 'mesh_tiny_cad': <module 'mesh_tiny_cad' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_tiny_cad\\__init__.py'>, 'development_api_navigator': <module 'development_api_navigator' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\development_api_navigator.py'>, 'object_edit_linked': <module 'object_edit_linked' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_edit_linked.py'>, 'io_import_images_as_planes': <module 'io_import_images_as_planes' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_import_images_as_planes.py'>, 'mesh_looptools': <module 'mesh_looptools' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_looptools.py'>, 'node_wrangler': <module 'node_wrangler' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\node_wrangler.py'>, 'mesh_inset': <module 'mesh_inset' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\mesh_inset\\__init__.py'>, 'io_import_scene_unreal_psa_psk': <module 'io_import_scene_unreal_psa_psk' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_import_scene_unreal_psa_psk.py'>, 'render_auto_tile_size': <module 'render_auto_tile_size' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\render_auto_tile_size.py'>, 'io_export_pc2': <module 'io_export_pc2' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_export_pc2.py'>, 'io_scene_3ds': <module 'io_scene_3ds' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_scene_3ds\\__init__.py'>, 'io_shape_mdd': <module 'io_shape_mdd' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_shape_mdd\\__init__.py'>, 'space_view3d_copy_attributes': <module 'space_view3d_copy_attributes' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_copy_attributes.py'>, 'object_fracture_cell': <module 'object_fracture_cell' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_fracture_cell\\__init__.py'>, 'io_mesh_uv_layout': <module 'io_mesh_uv_layout' from 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\io_mesh_uv_layout\\__init__.py'>}
==END==`

**Comment by alanscodelog** [comment]
This is quite puzzling...

What about when you install the addon, can you give me that exact output from when you started Blender to the message it displays when you install it.

Also have you tried installing any other addons, do they have the same problem or is it just this one?

**Comment by Gerkinfeltser** [comment]
Other addons present no problems. Output is as follows when installing ("......." used in place of actual paths)

`Modules Installed () from '.......blender-debugger-for-vscode-0.1.1.zip' into '.......\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons'`

**Comment by alanscodelog** [comment]
Phew, I think I found the problem. You downloaded the zip from the Releases didn't you? I think the periods in the name might be messing with Blender. Rename it to `blender-debugger-for-vscode-master.zip` like you'd get if you downloaded it directly from the clone or download button.

**Comment by Gerkinfeltser** [comment]
Hey, nice! Actually just renaming the script folder to exclude the periods made it show up.
Thanks so much for the continued assistance!!!

**Comment by alanscodelog** [comment]
No problem.

For anyone who stumbles upon this in the future, this is a known limitation. See this [blender issue](https://developer.blender.org/T50042).  Github doesn't seem to have a way to deal with this. And modules are named after their folders in Python and there doesn't seem to be a way around that, that I understand.

I will add this caveat to the documentation and/or the release notes.
